name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: unit tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: |
              pip install -r requirements.txt
              pytest tests.py

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 1
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"